export const ADVISOR_LIST_REQUEST = 'ADVISOR_LIST_REQUEST';
export const ADVISOR_LIST_SUCCESS = 'ADVISOR_LIST_SUCCESS';
export const ADVISOR_LIST_FAIL = 'ADVISOR_LIST_FAIL';

export const ADVISOR_DETAILS_REQUEST = 'ADVISOR_DETAILS_REQUEST';
export const ADVISOR_DETAILS_SUCCESS = 'ADVISOR_DETAILS_SUCCESS';
export const ADVISOR_DETAILS_FAIL = 'ADVISOR_DETAILS_FAIL';

export const DEGREEPROGRAM_LIST_REQUEST = 'DEGREEPROGRAM_LIST_REQUEST';
export const DEGREEPROGRAM_LIST_SUCCESS = 'DEGREEPROGRAM_LIST_SUCCESS';
export const DEGREEPROGRAM_LIST_FAIL = 'DEGREEPROGRAM_LIST_FAIL';

export const TIME_LIST_FAIL = 'TIME_LIST_FAIL';
export const TIME_LIST_REQUEST = 'TIME_LIST_REQUEST';
export const TIME_LIST_SUCCESS = 'TIME_LIST_SUCCESS';
