export const ADD_DETAILS = 'ADD_DETAILS';

export const MAKE_APPOINTMENT_REQUEST = 'MAKE_APPOINTMENT_REQUEST';
export const MAKE_APPOINTMENT_SUCCESS = 'MAKE_APPOINTMENT_SUCCESS';
export const MAKE_APPOINTMENT_FAIL = 'MAKE_APPOINTMENT_FAIL';
